#!/usr/bin/env python

from subprocess import Popen, PIPE
import socket

SEARCH_IPS = ["192.168.193.%d"%i for i in range(2,255)]
PORT = 23456


available_ips = []

pipes = []
for ip in SEARCH_IPS:
    pipes.append(Popen(["ping", "-c", "1", "-t", "1", ip], bufsize=1024, stdout=PIPE))

for p, ip in zip(pipes, SEARCH_IPS):
    if(p.wait() == 0):
        print('+', end='', flush=True)
        available_ips.append(ip)
    else:
        print('.', end='', flush=True)

for ip in available_ips:
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(0.1)
        s.connect((ip, PORT))
        s.send(b"BBB?\n")
        if s.recv(128) == b'yes':
            print(ip)
            break
    except Exception as e:
        pass
